public class Comments {

    public static void main(String[] args) {
	    // Single Line Comment

      // Right here we have our ready, set, go! to print:
      System.out.println("Ready");
      System.out.println("Set");
      System.out.println("Go!");

      /*
      This is a multi-line comment!
      Everything in this will be commented out as well,
      and we can have multiple lines in here too
      */
    }
}
